Repository bigbinary/acehelp, pull requests merged in 2018-09, with the labels that each got.

#501 Restricts elm-form-field to install version 1.0.0 by default.
  elm-package.json
Labels: bug

#493 Moves HTML out of Main to Page.View module.
  app/javascript/Admin/Main.elm
  app/javascript/Admin/Page/View.elm
Labels: Low Priority

#599 Add cancel button to create article page
  app/assets/stylesheets/admin/article.scss
  app/javascript/Admin/Main.elm
  app/javascript/Admin/Page/Article/Create.elm
Labels: PR
